// Code generated by goctl. DO NOT EDIT.
package types

type GetShortUrlRequest struct {
	Url string `json:"url"`
}

type GetShortUrlResponse struct {
	ShortUrl string `json:"short_url"`
}

type GetLongUrlRequest struct {
	ShortUrl string `json:"short_url"`
}

type GetLongUrlResponse struct {
	Url string `json:"url"`
}
