// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"shorturl-service/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/short",
				Handler: GetShortUrlHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/long",
				Handler: GetLongUrlHandler(serverCtx),
			},
		},
	)
}
